// SPDX-License-Identifier: GPL-3.0-or-later
// THE FRAME - one turn of the viewer's loop, out of `main` by
// `todo/play-split.md` (2026-10-02).
//
// `PlayFrame` holds a REFERENCE to every local of `main` the loop body uses,
// under the local's own name, and a `FunctionRef` to every lambda it calls -
// so `step()`, the body, reads exactly as it did inside `main` and moved byte
// for byte. The list was taken from clang's AST (`-ast-dump=json`): the
// names the body refers to, with their declared types. `main` builds one with
// designated initializers, which the compiler checks name by name.
//
// `step()` returns -1 to go round again, -2 where the body said `break` (the
// window closed, the quit confirmed), and anything else as `main`'s exit code
// (the body's one `return 1`, a script's screen missing from the tree).
#pragma once

#include "playshared.h"
#include "app/functionref.h"

struct PlayFrame {
    const std::string & fr;
    int & frames;
    std::string & dump;
    std::string & typeText;
    int & dispW;
    int & dispH;
    std::vector<int> & scripted;
    int & keyEvery;
    std::string & snapsDir;
    std::string & flickerDir;
    bool & waterCamPreset;
    int & snapEvery;
    std::string & savesPath;
    int & density;
    int & fightArg;
    bool & noFightCamRay;
    int & fightLevelArg;
    bool & boardArg;
    bool & densityFlag;
    bool & clipFlag;
    int & skyFlag;
    int & shadowFlag;
    bool & cpuBodiesFlag;
    int & detailFlag;
    bool & dither;
    bool & mouseInvertX;
    float & shootEyeLift;
    bool & shootEyeSet;
    bool & drawFog;
    bool & lightCrowd;
    std::uint8_t (&fogRGB)[3];
    bool & noScriptSprites;
    std::vector<int> & scxPlay;
    bool & openSneak;
    bool & startShoot;
    int & shootHealth;
    long & shootEndAt;
    float (&standAt)[4];
    bool & haveStand;
    float (&eyeA)[3];
    float (&atA)[3];
    float & fovA;
    int & callDialog;
    bool & animHoldHarness;
    bool & haveEye;
    bool & haveAt;
    double & speed;
    bool & showFps;
    bool& boardPress;
    bool& mountSpent;
    bool& calledOpenTold;
    bool& boarded;
    bool& boarding;
    float (&doorOff)[3];
    int& doorOffState;
    double& boardCam;
    bool& leaving;
    float (&exitOff)[3];
    int& exitOffState;
    omk::NodeTracks& doorIn;
    omk::NodeTracks& doorOut;
    bool& doorClipsRead;
    int& journeyTo;
    int& calledDestination;
    std::optional<omk::SliderRide>& ride;
    bool& scxPlayed;
    float (&savedAt)[3];
    float& savedYaw;
    bool& haveSavedPlacement;
    const omk::DataFs& fs;
    omk::UiWidgets& w;
    omk::TextLayout& lay;
    omk::ScreenComposer& comp;
    omk::OptionsMenu& optMenu;
    omk::Surface& view3dPic;
    omk::MenuCloud& cloud;
    omk::Input& in;
    omk::GameState& state;
    std::string& loadedName;
    std::optional<omk::SettingsBlock>& saveSettings;
    omk::Settings& settings;
    omk::FunctionRef<float()> fxGain;
    omk::FunctionRef<float()> dialogueGain;
    std::array<std::pair<std::string, int>, 20>& highScores;
    const bool& unlimitedClip;
    double& clipInches;
    bool& clipReport;
    std::vector<std::vector<std::uint16_t>>& flickRing;
    std::vector<std::string>& flickNote;
    std::vector<long>& flickLit;
    std::string& frameNote;
    int& flickAfter;
    long& flickEvent;
    long& flickQuietUntil;
    bool& drawSky;
    bool& drawShadows;
    const bool& threadBodies;
    int& shadowQuality;
    int& shadowDetail;
    int& lighting;
    const bool& radarAlways;
    const int& frameRate;
    omk::FunctionRef<void(int, int)> applyTextScale;
    bool& forceAdventure;
    const std::vector<omk::ObjectRecord>& objectRecords;
    const std::vector<std::byte>& globalFile;
    omk::Inventory& inv;
    const std::vector<omk::Destination>& destinations;
    bool& sliderTold;
    std::string& examineTold;
    std::string& examineText;
    std::string& memoBodyPending;
    omk::Session& session;
    std::unique_ptr<omk::UiWalk>& walk;
    int& openScreen;
    int& conversations;
    int& lastArea;
    omk::LoadPanel& loadPanelState;
    int& pendingLoadSlot;
    bool& quitRequested;
    bool& exitProgram;
    bool& videophoneCall;
    bool& videophoneSpoke;
    bool& callHarness;
    int& callPending;
    omk::UiCursor& uiCursor;
    omk::UiListState& uiLists;
    omk::UiModels& uiModels;
    bool& screenFromScript;
    std::uint32_t& screenOpenBits;
    int& playerScreen;
    bool& actionSpent;
    std::map<std::uint32_t, std::string>& sneakRows;
    std::vector<std::uint8_t>& addrSeen;
    std::set<std::uint32_t>& sneakHidden;
    int& sneakTold;
    int& replySel;
    int& actionTold;
    std::uint32_t& prevBits;
    omk::SpecialMoves& specialMoves;
    const omk::CityMaps& cityMaps;
    const omk::ShootWeaponTable& shootWeapons;
    std::map<std::pair<int, int>, int>& sceneVoices;
    omk::FunctionRef<void(const char *, std::size_t, int, int, float, const float *)> sfxLog;
    int& takeCandidate;
    bool& takeWasLow;
    int& heldInHand;
    int& lineScroll;
    int& lineOverflow;
    bool& menuShown;
    int& lastDlgCam;
    std::vector<omk::CameraRay>& worldRays;
    int& lastRayCam;
    int& editingShown;
    bool& haveLastDrawn;
    float (&lastEye)[3];
    float (&lastAt)[3];
    float& lastFov;
    std::vector<CtlSpriteInst>& ctlSprites;
    int& ctlFxState;
    float& ctlFxFrame;
    std::vector<CtlSpriteInst>& foeSprites;
    int& foeFxState;
    float& foeFxFrame;
    long& foeSpritesDrawn;
    long& foeSpritesPooled;
    omk::ParticleField& ctlField;
    omk::Geometry& ctlGeo;
    bool& takeCam;
    int& takeCamPhase;
    float& takeCamClock;
    float (&takeCamFromEye)[3];
    float (&takeCamFromAt)[3];
    float& takeCamFromFov;
    float (&takeCamEye)[3];
    float (&takeCamAt)[3];
    float& takeCamFov;
    float& takeCamTravel;
    omk::FunctionRef<void(int)> takeCamRequest;
    omk::FunctionRef<void(const float *, const float *, float, float)> playerCamRequest;
    bool& fallBanded;
    omk::FunctionRef<void(int, bool, const char *, int)> fallCamRequest;
    float& lastRoll;
    bool& musicPaused;
    bool& holdEditCam;
    unsigned long& heldUnderRequests;
    bool& editFromKnown;
    float (&editFromEye)[3];
    float (&editFromAt)[3];
    float& editFromFov;
    float& editFromRoll;
    bool& rollTold;
    std::unique_ptr<omk::PlayerController>& player;
    omk::CtlFile& playerCtl;
    int& moveWaitCtx;
    int& moveWaitGroup;
    std::vector<std::byte>& playerCtlData;
    std::vector<omk::Mesh>& playerMeshes;
    omk::MeshNameIndex& playerBoneIdx;
    std::vector<omk::Texture>& playerTex;
    omk::Geometry& playerRest;
    omk::Geometry& playerPosed;
    std::vector<float>& playerAffine;
    long& playerPosedFrame;
    std::vector<omk::CollisionSphere>& playerSpheres;
    float& playerReach;
    omk::TriangleSoup& playerSoup;
    std::vector<std::uint32_t>& playerSoupFlags;
    const float *& soupFlagsFor;
    std::size_t& soupFlagsSize;
    omk::SplitSoupGrid& playerGrid;
    std::vector<std::uint8_t>& playerMovingTri;
    std::vector<std::uint32_t>& playerMovingIds;
    omk::FunctionRef<void()> rebuildFixedGrid;
    omk::FunctionRef<void()> rebuildMovingGrid;
    bool& mergedValid;
    omk::TriangleSoup& playerSteep;
    omk::SplitSoupGrid& playerSteepGrid;
    std::vector<std::uint8_t>& steepMovingTri;
    std::vector<std::uint32_t>& steepMovingIds;
    omk::FunctionRef<void()> rebuildSteepFixedGrid;
    omk::FunctionRef<void()> rebuildSteepMovingGrid;
    std::string& playerModel;
    std::string& playerCtlName;
    bool& adventure;
    bool& playerReady;
    bool& followCam;
    bool& playerProgram;
    bool& playerProgramWas;
    bool& mirrorLive;
    bool& mirrorSeen;
    float (&playerHeadAt)[3];
    float& playerHeadRise;
    bool& playerHeadKnown;
    std::vector<float>& playerMeshAt;
    std::vector<float>& playerMeshRot;
    bool& playerMeshAtKnown;
    int& placementSeen;
    long& heldFrames;
    std::string& mediaText;
    double& mediaTextFrames;
    omk::Surface& mediaBmp;
    float& playerFeet;
    bool& playerFeetKnown;
    float& playerRootRef;
    bool& playerStandLatched;
    float (&playerRootXZ)[2];
    float& lastRootDrop;
    int& playerCamId;
    float& handoverFacing;
    bool& handoverFacingKnown;
    bool& playerDrivenSeen;
    int& playerDrivenArea;
    double& frameSec;
    double& gameClock;
    std::vector<HoldRun>& holds;
    long& handoverFrame;
    std::vector<float> & sndMove;
    std::vector<float> & sndConfirm;
    std::vector<float> & sndBack;
    std::vector<float> & optSndMove;
    std::vector<float> & optSndConfirm;
    std::vector<float> & optSndBack;
    const omk::UiWalk *& optWalkSeen;
    bool& optEntered;
    std::pair<int, int>& pendingDisplay;
    omk::FunctionRef<std::vector<float>(int, int)> loadSlot;
    SdlFrontend& front;
    omk::Renderer *& vkRen;
    omk::Renderer *& worldVk;
    SDL_Window *& glWin;
    omk::Renderer *& glRen;
    double& glSwapMs;
    omk::FunctionRef<void(const omk::Surface &)> present;
    omk::FunctionRef<void(const std::vector<float> &)> blip;
    const omk::AdpcmTables & adpcmTables;
    omk::MusicPlayer & music;
    int & playingTrack;
    omk::VoiceOverLibrary & voiceLib;
    omk::VoiceOverPlayer & voices;
    int & voiceOverShot;
    std::vector<omk::Mesh>& speakerMeshes;
    omk::NodeTracks& speakerTracks;
    float& lineIdleFrame;
    float& sceneFrameLast;
    std::shared_ptr<const std::vector<std::byte>>& speakerMorph;
    std::string& speakerModel;
    std::string& speakerVoice;
    int& voiceShot;
    float (&speakerAt)[3];
    bool& speakerSolved;
    bool& speakerReady;
    int& speakerConv;
    bool& dialogMode;
    bool& shootMode;
    std::map<std::string, CharModel>& charModels;
    std::map<std::string, PropModel>& propModels;
    omk::Geometry& propGeo;
    std::vector<const PropModel *>& propBatchOwner;
    std::set<int>& propsTold;
    std::vector<std::unique_ptr<Staged>>& staged;
    std::vector<PedJob>& pedJobs;
    std::vector<std::unique_ptr<PedStaged>>& pedStaged;
    std::map<std::pair<const omk::NodeTracks *, int>, omk::NodeTracks>& pedLodTracks;
    omk::FunctionRef<int(const CharModel &, const omk::NodeTracks &)> skeletonRootOf;
    omk::FunctionRef<bool(const CharModel &)> hasSeveralSkeletons;
    omk::FunctionRef<int(const CharModel &)> lodChainOf;
    omk::FunctionRef<const omk::NodeTracks *(const omk::NodeTracks *, int, int)> lodTracksFor;
    omk::FunctionRef<const omk::Geometry &(const std::string &, const CharModel &, int)> lodRestFor;
    std::vector<std::unique_ptr<VehStaged>>& vehStaged;
    int& vehDrawn;
    int& vehLive;
    int& vehStopped;
    long& vehTold;
    omk::FunctionRef<int(const CharModel &)> heaviestRootOf;
    std::map<std::pair<int, int>, omk::NodeTracks>& pedTracks;
    long& pedCacheGen;
    std::vector<std::byte>& pedAni;
    std::string& pedAniName;
    int& pedDrawn;
    int& pedLive;
    int& pedInAction;
    int& pedIdle;
    int& pedOffView;
    int& pedLit;
    long& pedTold;
    std::map<int, std::vector<omk::PedClip>>& shootClips;
    omk::FunctionRef<const omk::PedClip *(int, int)> shootClipFor;
    omk::FunctionRef<const omk::PedClip *(int, int)> shootClipOfType;
    omk::FunctionRef<const omk::PedClip *(int, int)> shootClipExact;
    omk::FunctionRef<const omk::PedClip *(int, int)> shootClipBySlot;
    omk::FunctionRef<const omk::NodeTracks *(int, const omk::PedClip &, const std::vector<omk::Mesh> &)> pedTracksFor;
    bool& shootCameraLive;
    float& shootPitch;
    std::map<int, omk::ShootRecord>& shootBrains;
    std::map<int, long>& gunShots;
    std::set<int>& gunTold;
    std::map<int, GunClip>& gunClips;
    std::map<int, GunAnim>& gunAnims;
    std::map<int, int>& gunCurType;
    std::map<int, int>& gunCurSlot;
    float& playerDeathCountdown;
    std::set<int>& gunStandDown;
    std::set<int>& gunLooped;
    std::map<int, GunAim>& gunAims;
    std::set<int>& gunAimTold;
    std::set<int>& gunDrawnTold;
    std::set<int>& gunBarrelTold;
    int& hudHealth;
    std::uint32_t& gunRandSeed;
    omk::ShootRecord& playerShootRec;
    omk::ShotLatch& shotLatch;
    omk::ShootAim& shootAim;
    omk::ShootMover& shootMover;
    std::unique_ptr<omk::UiWalk>& hudWalk;
    omk::HudBar& hudBar;
    omk::Radar& radar;
    omk::Map2d& shootMap;
    omk::ShootField& shootField;
    std::set<int>& gunCellSeeded;
    std::set<int>& gunEntryPending;
    omk::FunctionRef<void(long, int, const float *, const char *)> shootNoise;
    std::map<std::uint32_t, std::string>& hudRows;
    int& hudAmmo;
    std::string& hudTold;
    long& shootMoveFrames;
    float& shootMoveDist;
    float (&shootMoveFrom)[3];
    const int& mouseSensX;
    const int& mouseSensY;
    const bool& mouseInverted;
    bool& shootPitchDirty;
    omk::FunctionRef<std::vector<omk::MeshPose>(omk::PlayerController *, bool, const omk::NodeTracks &, float)> playerPoseNow;
    omk::FunctionRef<std::vector<omk::MeshPose>(int, int, const CharModel *, const omk::NodeTracks &, float)> gunmanPoseNow;
    omk::ProjectilePool& projectiles;
    long& shotsFired;
    omk::SfxFile& shootSfx;
    std::unique_ptr<omk::ScxRuntime>& shootRt;
    std::map<std::pair<const std::byte *, std::size_t>, SfxSample>& sfxCache;
    std::string& sfxSceneWas;
    omk::FunctionRef<const SfxSample &(std::span<const std::byte>)> sfxPcm;
    omk::FunctionRef<void(long, int, const float *, const float *, const char *)> shotSound;
    std::string& shotGunStem;
    omk::FunctionRef<const GunFacts &(const std::string &)> gunFactsFor;
    long& stagedEver;
    std::vector<int>& stagedIds;
    std::uint64_t& poolComposition;
    std::uint64_t& poolBuiltFor;
    std::uint64_t& poolTold;
    bool& poolHasSprites;
    bool& poolHasPlayer;
    std::size_t& playerTexBase;
    std::size_t& spriteTexBase;
    std::unordered_map<int, int>& spriteSlot;
    std::set<int>& spriteWanted;
    std::set<int>& spritePooled;
    bool& poolOverflowTold;
    const bool& stagedProbe;
    const bool& obstructProbe;
    const float& progYawSign;
    omk::FunctionRef<CharModel *(const std::string &)> charModelFor;
    omk::FunctionRef<PropModel *(const std::string &)> propModelFor;
    omk::FunctionRef<CharBank *(const std::string &)> charBankFor;
    FightRun& fightRun;
    bool& fightCamTold;
    omk::FunctionRef<bool(int, int)> beginMelee;
    omk::FunctionRef<omk::NodeTracks(const CharBank &, const std::vector<omk::Mesh> &)> idleTracksFor;
    std::vector<omk::Texture>& pool;
    std::size_t& poolSize;
    SpriteTable& spriteTab;
    const omk::SpriteLookup& spriteLookup;
    std::unique_ptr<omk::ScxRuntime>& globalRt;
    std::unique_ptr<omk::ScxRuntime>& fightRt;
    omk::FunctionRef<void()> refreshSprites;
    omk::SoftwareRenderer& worldSw;
    omk::Renderer & world;
    bool& worldReady;
    std::array<WorldSlot, 2>& worldSlots;
    std::string& worldSet;
    std::size_t (&worldTexBase)[2];
    unsigned int& worldGen;
    Sky& sky;
    const omk::ShadowModel& shadowModel;
    omk::Geometry& shadowGeo;
    std::size_t& shadowTexBase;
    float& pedFootOffMax;
    float& shadowFootOffMax;
    float& shadowSpreadMax;
    float& shadowSpreadPlayer;
    long& shadowBlobsDrawn;
    bool& lightsTold;
    bool& shadowLightTold;
    bool& shadowTold;
    float& shimmerClock;
    std::vector<omk::DecorSoup>& worldDecors;
    std::uint64_t& worldGeoRev;
    std::vector<omk::Texture>& worldTex;
    long& worldFrames;
    omk::Geometry& fxGeo;
    float (&actorAt)[3];
    bool& actorKnown;
    int& lastCamera;
    std::shared_ptr<SetLoad> (&setLoads)[2];
    std::string (&slotAsked)[2];
    int (&slotAskedArea)[2];
    const bool& syncSets;
    const bool& loadGate;
    omk::FunctionRef<bool(int, const std::string &, int, long)> askSet;
    omk::FunctionRef<bool(SetLoad &, long)> integrateSet;
    omk::FunctionRef<void()> rebuildWorld;
    omk::HostInput& host;
    omk::Surface& fb;
    long& n;
    Uint32& lastMs;
    omk::FunctionRef<long()> uiClockMs;
    Uint32& fpsLastMs;
    Uint32& fpsWorst;
    Uint32& fpsSince;
    int& fpsFrames;
    float (&spriteAnchor)[3];
    bool& spriteAnchorSet;
    std::map<int, long>& spriteLogged;
    omk::FunctionRef<void(long, int, const char *, int, int, const omk::HitOut &)> applyPlayerDamage;
    std::set<std::string>& motionLogged;
    double& paceNext;
    omk::FunctionRef<double()> phaseNow;
    double& phTop;
    double& phRb0;
    double& phRb1;
    std::vector<std::pair<const char *, double>>& phMarks;
    omk::FunctionRef<void(const char *)> mark;
    std::map<std::string, double>& phSpan;
    std::map<std::string, double>& phSection;
    omk::FunctionRef<void(const char*, omk::FunctionRef<void()>)> spanned;
    double (&phSum)[4];
    long& phN;
    long& phGpu;
    std::map<std::string, long>& phKept;

    int step();
};
